// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ProjectCore.Infrastructure;
using System;

namespace ProjectCore.Infrastructure.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20180507095339_MigD8")]
    partial class MigD8
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectCore.Domain.Model.DomainModel.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<int?>("CustomerAddrId");

                    b.Property<string>("CustomerAge");

                    b.Property<string>("CustomerName");

                    b.Property<string>("CustomerPhone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAddrId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ProjectCore.Domain.Model.DomainModel.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CustomrId");

                    b.Property<string>("OrderCreateDate");

                    b.Property<int>("OrderPrice");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProjectCore.Domain.Model.DomainModel.OrderDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("OrderDetailPrice");

                    b.Property<Guid>("OrderId");

                    b.Property<int>("OrderNumBer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("ProjectCore.Domain.Model.DomainModel.ShoppingCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("CartTotalPrice");

                    b.Property<string>("Code");

                    b.Property<Guid>("CustomerId");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("ProjectCore.Domain.Model.DomainModel.ShoppingCartDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<Guid>("ProductId");

                    b.Property<string>("ShopProductColor");

                    b.Property<string>("ShopProductName");

                    b.Property<int>("ShopProductNumBer");

                    b.Property<double>("ShopProductPrice");

                    b.Property<Guid>("ShoppingCartId");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("ShoppingCartDetails");
                });

            modelBuilder.Entity("ProjectCore.Domain.Model.DomainValueObject.CustomerAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddrCity");

                    b.Property<string>("AddrCounty");

                    b.Property<string>("AddrProvince");

                    b.Property<string>("Address");

                    b.HasKey("Id");

                    b.ToTable("CustomerAddress");
                });

            modelBuilder.Entity("ProjectCore.Domain.Model.DomainModel.Customer", b =>
                {
                    b.HasOne("ProjectCore.Domain.Model.DomainValueObject.CustomerAddress", "CustomerAddr")
                        .WithMany()
                        .HasForeignKey("CustomerAddrId");
                });

            modelBuilder.Entity("ProjectCore.Domain.Model.DomainModel.OrderDetails", b =>
                {
                    b.HasOne("ProjectCore.Domain.Model.DomainModel.Order", "OrderInfo")
                        .WithMany("OrderDetailList")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProjectCore.Domain.Model.DomainModel.ShoppingCartDetails", b =>
                {
                    b.HasOne("ProjectCore.Domain.Model.DomainModel.ShoppingCart", "ShoppingCart")
                        .WithMany("ShoppingCartDetailList")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
